'use client';

import {
  DocsPage,
  DocsBody,
  DocsDescription,
  DocsTitle,
} from 'fumadocs-ui/page';
import defaultMdxComponents from 'fumadocs-ui/mdx';
import { DocsLayout } from 'fumadocs-ui/layouts/docs';
import {
  Note,
  Steps,
  Step,
  FeatureGrid,
  FeatureCard,
  Badge,
  VersionBadge,
  PackageBadge,
  TerminalBlock,
  CodeGroup,
  FrameworkBadge,
  ComparisonTable,
  Accordion,
  CodeBlock,
  ArchitectureDiagram,
  ArchBox,
  ArchConnector,
  ArchRow,
  FlowDiagram,
  FlowNode,
  FlowArrow,
  FileTree,
  FileTreeFile,
  FileTreeDir,
  APIBox,
  PropsTable,
  KeyboardShortcut,
  ShortcutList,
  CopyButton,
} from '@/components';

export {
  DocsPage,
  DocsBody,
  DocsDescription,
  DocsTitle,
  defaultMdxComponents,
  DocsLayout,
  Note,
  Steps,
  Step,
  FeatureGrid,
  FeatureCard,
  Badge,
  VersionBadge,
  PackageBadge,
  TerminalBlock,
  CodeGroup,
  FrameworkBadge,
  ComparisonTable,
  Accordion,
  CodeBlock,
  ArchitectureDiagram,
  ArchBox,
  ArchConnector,
  ArchRow,
  FlowDiagram,
  FlowNode,
  FlowArrow,
  FileTree,
  FileTreeFile,
  FileTreeDir,
  APIBox,
  PropsTable,
  KeyboardShortcut,
  ShortcutList,
  CopyButton,
};
