/**
 * Constants Module
 *
 * @module constants
 */

export {
  DEFAULT_STALE_TIME,
  DEFAULT_GC_TIME,
  DEFAULT_RETRY_COUNT,
  DEFAULT_RETRY_DELAY,
  DEFAULT_RETRY_BACKOFF,
  MAX_QUERY_KEY_DEPTH,
  MAX_OBSERVER_COUNT,
  MIN_CACHE_SIZE,
  MAX_CACHE_SIZE,
  RUNTIME_VERSION,
} from './defaults';
